apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: podinfo-ui
  namespace: guestbook
spec:
  to:
    kind: Service
    name:  podinfo-ui
    weight: 100
  port:
    targetPort: 9898
  tls:
    termination: edge
